
package ru.mera.ivstepan.carshowroom.soap.service.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ru.mera.ivstepan.carshowroom.soap.service.DeleteOrderElement;
import ru.mera.ivstepan.carshowroom.soap.service.GetAllOrderElement;
import ru.mera.ivstepan.carshowroom.soap.service.GetOrderRequestElement;
import ru.mera.ivstepan.carshowroom.soap.service.GetOrderResponseElement;
import ru.mera.ivstepan.carshowroom.soap.service.ObjectFactory;
import ru.mera.ivstepan.carshowroom.soap.service.SaveCustomerElement;
import ru.mera.ivstepan.carshowroom.soap.service.SaveOrderElement;
import ru.mera.ivstepan.carshowroom.soap.service.UpdateOrderElement;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapService", targetNamespace = "http://service.soap.carshowroom.ivstepan.mera.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapService {


    /**
     * 
     * @param saveOrderElement
     */
    @WebMethod
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://service.soap.carshowroom.ivstepan.mera.ru/", className = "ru.mera.ivstepan.carshowroom.soap.service.CreateOrder")
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://service.soap.carshowroom.ivstepan.mera.ru/", className = "ru.mera.ivstepan.carshowroom.soap.service.CreateOrderResponse")
    public void createOrder(
        @WebParam(name = "SaveOrderElement", targetNamespace = "")
        SaveOrderElement saveOrderElement);

    /**
     * 
     * @param getOrderElement
     * @return
     *     returns java.util.List<ru.mera.ivstepan.carshowroom.soap.service.GetOrderResponseElement>
     */
    @WebMethod
    @WebResult(name = "getCustomerOrders", targetNamespace = "")
    @RequestWrapper(localName = "getCustomerOrders", targetNamespace = "http://service.soap.carshowroom.ivstepan.mera.ru/", className = "ru.mera.ivstepan.carshowroom.soap.service.GetCustomerOrders")
    @ResponseWrapper(localName = "getCustomerOrdersResponse", targetNamespace = "http://service.soap.carshowroom.ivstepan.mera.ru/", className = "ru.mera.ivstepan.carshowroom.soap.service.GetCustomerOrdersResponse")
    public List<GetOrderResponseElement> getCustomerOrders(
        @WebParam(name = "GetOrderElement", targetNamespace = "")
        GetOrderRequestElement getOrderElement);

    /**
     * 
     * @param saveCustomerElement
     */
    @WebMethod
    @RequestWrapper(localName = "createCustomer", targetNamespace = "http://service.soap.carshowroom.ivstepan.mera.ru/", className = "ru.mera.ivstepan.carshowroom.soap.service.CreateCustomer")
    @ResponseWrapper(localName = "createCustomerResponse", targetNamespace = "http://service.soap.carshowroom.ivstepan.mera.ru/", className = "ru.mera.ivstepan.carshowroom.soap.service.CreateCustomerResponse")
    public void createCustomer(
        @WebParam(name = "SaveCustomerElement", targetNamespace = "")
        SaveCustomerElement saveCustomerElement);

    /**
     * 
     * @param updateOrderElement
     */
    @WebMethod
    @RequestWrapper(localName = "updateOrder", targetNamespace = "http://service.soap.carshowroom.ivstepan.mera.ru/", className = "ru.mera.ivstepan.carshowroom.soap.service.UpdateOrder")
    @ResponseWrapper(localName = "updateOrderResponse", targetNamespace = "http://service.soap.carshowroom.ivstepan.mera.ru/", className = "ru.mera.ivstepan.carshowroom.soap.service.UpdateOrderResponse")
    public void updateOrder(
        @WebParam(name = "UpdateOrderElement", targetNamespace = "")
        UpdateOrderElement updateOrderElement);

    /**
     * 
     * @param deleteOrderElement
     */
    @WebMethod
    @RequestWrapper(localName = "deleteOrder", targetNamespace = "http://service.soap.carshowroom.ivstepan.mera.ru/", className = "ru.mera.ivstepan.carshowroom.soap.service.DeleteOrder")
    @ResponseWrapper(localName = "deleteOrderResponse", targetNamespace = "http://service.soap.carshowroom.ivstepan.mera.ru/", className = "ru.mera.ivstepan.carshowroom.soap.service.DeleteOrderResponse")
    public void deleteOrder(
        @WebParam(name = "DeleteOrderElement", targetNamespace = "")
        DeleteOrderElement deleteOrderElement);

    /**
     * 
     * @return
     *     returns java.util.List<ru.mera.ivstepan.carshowroom.soap.service.GetAllOrderElement>
     */
    @WebMethod
    @WebResult(name = "getAllOrders", targetNamespace = "")
    @RequestWrapper(localName = "getAllOrders", targetNamespace = "http://service.soap.carshowroom.ivstepan.mera.ru/", className = "ru.mera.ivstepan.carshowroom.soap.service.GetAllOrders")
    @ResponseWrapper(localName = "getAllOrdersResponse", targetNamespace = "http://service.soap.carshowroom.ivstepan.mera.ru/", className = "ru.mera.ivstepan.carshowroom.soap.service.GetAllOrdersResponse")
    public List<GetAllOrderElement> getAllOrders();

}
