FROM openjdk:8-jre-alpine
EXPOSE 8082
ADD /build/libs/ClientAutoshowroomREST.jar ClientAutoshowroomREST.jar
#CMD java - jar ClientAutoshowroomREST.jar
ENTRYPOINT ["java","-jar","ClientAutoshowroomREST.jar"]
