FROM openjdk:8-jre-alpine
EXPOSE 8080
ADD /build/libs/ClientAutoshowroomSoAP-1.0.0.jar ClientAutoshowroomSoAP-1.0.0.jar
#CMD java - jar ClientAutoshowroomSoAP-1.0.0.jar
ENTRYPOINT ["java","-jar","ClientAutoshowroomSoAP-1.0.0.jar"]
